name: weather
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mockito: ^5.5.0
  build_runner: ^2.7.1
  envied: ^1.3.1
  dio: ^5.9.0
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: ^1.26.2
  envied_generator: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/day.svg
    - assets/icons/night.svg

  fonts:
    - family: BebasNeue
      fonts: 
        - asset: fonts/BebasNeue-Regular.ttf